using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CarolusNexus.Services;

public static class HumanApprovalCenterService
{
    public static string StorePath => Path.Combine(AppPaths.DataDir, "approval-center.json");

    public sealed class ApprovalItem
    {
        [JsonPropertyName("id")]
        public string Id { get; set; } = Guid.NewGuid().ToString("N");

        [JsonPropertyName("createdUtc")]
        public DateTime CreatedUtc { get; set; } = DateTime.UtcNow;

        [JsonPropertyName("title")]
        public string Title { get; set; } = "";

        [JsonPropertyName("risk")]
        public string Risk { get; set; } = "medium";

        [JsonPropertyName("status")]
        public string Status { get; set; } = "pending";

        [JsonPropertyName("reason")]
        public string Reason { get; set; } = "";
    }

    public sealed class ApprovalDocument
    {
        [JsonPropertyName("version")]
        public int Version { get; set; } = 1;

        [JsonPropertyName("items")]
        public List<ApprovalItem> Items { get; set; } = new();
    }

    public static ApprovalDocument Load()
    {
        try
        {
            if (!File.Exists(StorePath))
                return new ApprovalDocument();
            return JsonSerializer.Deserialize<ApprovalDocument>(File.ReadAllText(StorePath)) ?? new ApprovalDocument();
        }
        catch
        {
            return new ApprovalDocument();
        }
    }

    public static string SeedDemoApproval()
    {
        var doc = Load();
        if (!doc.Items.Any(i => i.Status == "pending"))
        {
            doc.Items.Add(new ApprovalItem
            {
                Title = "Review generated operator flow before execution",
                Risk = "medium",
                Reason = "Generated by AI; requires human approval before write/post/send steps."
            });
            Save(doc);
        }

        return BuildReport();
    }

    public static string BuildReport()
    {
        var doc = Load();
        var sb = new StringBuilder();
        sb.AppendLine("Human-in-the-loop Approval Center");
        sb.AppendLine($"Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"Pending: {doc.Items.Count(i => i.Status == "pending")}");
        sb.AppendLine();
        if (doc.Items.Count == 0)
        {
            sb.AppendLine("No approval items yet.");
        }
        else
        {
            foreach (var item in doc.Items.OrderByDescending(i => i.CreatedUtc).Take(20))
                sb.AppendLine($"- {item.Status} | {item.Risk} | {item.Title} | {item.Reason}");
        }

        sb.AppendLine();
        sb.AppendLine("Allowed decisions: approve, reject, dry-run only, revise flow.");
        return sb.ToString().TrimEnd();
    }

    private static void Save(ApprovalDocument doc)
    {
        Directory.CreateDirectory(AppPaths.DataDir);
        File.WriteAllText(StorePath, JsonSerializer.Serialize(doc, new JsonSerializerOptions { WriteIndented = true }));
    }
}
